import Head from "next/head";
import FAQ from "src/components/FAQ";
import Footer from "src/components/Footer";
import GeneralInfo from "src/components/GeneralInfo";
import Header from "src/components/Header";
import HeaderInfo from "src/components/HeaderInfo";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <HeaderInfo />
      <GeneralInfo />
      <FAQ />
      <Footer />
    </>
  );
}
